[package]
name = "potenad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.5.2", features = ["canvas", "tokio", "debug", "glow"] }
tokio = { version = "1.22.0", features = ["full"] }
